_wandb:
    value:
        cli_version: 0.23.0
        e:
            pogs2xyno4rck1mehobw01hjw3l1vot9:
                codePath: train_tpu_256.py
                codePathLocal: train_tpu_256.py
                cpu_count: 56
                cpu_count_logical: 112
                disk:
                    /:
                        total: "103865303040"
                        used: "63253405696"
                email: mkkang0412@gmail.com
                executable: /home/mkkang0412/Ouroboros/.venv/bin/python
                git:
                    commit: bf99d6a4cb1b6cc6e7e7586ebd4819fee1116e31
                    remote: https://github.com/MK040412/Ouroboros.git
                host: t1v-n-8dff5040-w-0
                memory:
                    total: "202573803520"
                os: Linux-6.5.0-1013-gcp-x86_64-with-glibc2.35
                program: /home/mkkang0412/Ouroboros/train_tpu_256.py
                python: CPython 3.10.12
                root: /home/mkkang0412/Ouroboros
                startedAt: "2025-12-02T23:05:38.023663Z"
                tpu:
                    count: 4
                    devicesPerChip: 1
                    hbmGib: 16
                    name: v5e
                writerId: pogs2xyno4rck1mehobw01hjw3l1vot9
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 12
                - 45
            "2":
                - 1
                - 12
                - 45
            "3":
                - 13
                - 16
            "4": 3.10.12
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
depth:
    value: 4
global_batch_size:
    value: 2048
learning_rate:
    value: 0.5
model_dim:
    value: 896
num_epochs:
    value: 20
tread_selection_rate:
    value: 0.5
warmup_steps:
    value: 1000
