_wandb:
    value:
        cli_version: 0.23.0
        e:
            3ei5zi4bcqootg7yzgrmjevcsieiif8s:
                codePath: train_tpu_256_112cores.py
                codePathLocal: train_tpu_256_112cores.py
                email: mkkang0412@gmail.com
                executable: /home/mkkang0412/Ouroboros/.venv/bin/python
                git:
                    commit: 0f9ea4b8e98a4bf1141c665f694d1bbb4f22ce61
                    remote: https://github.com/MK040412/Ouroboros.git
                host: t1v-n-8dff5040-w-0
                os: Linux-6.5.0-1013-gcp-x86_64-with-glibc2.35
                program: /home/mkkang0412/Ouroboros/train_tpu_256_112cores.py
                python: CPython 3.10.12
                root: /home/mkkang0412/Ouroboros
                startedAt: "2025-12-02T22:51:05.107174Z"
                writerId: 3ei5zi4bcqootg7yzgrmjevcsieiif8s
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 12
                - 45
            "2":
                - 1
                - 12
                - 45
                - 49
            "3":
                - 13
                - 16
            "4": 3.10.12
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
global_batch_size:
    value: 7168
learning_rate:
    value: 0.5
num_devices:
    value: 112
num_epochs:
    value: 20
tread_selection_rate:
    value: 0.5
