_wandb:
    value:
        cli_version: 0.23.0
        e:
            37e4t5g4o1mvmbkep8j769rzjeqowf55:
                codePath: train_tpu_256_112cores.py
                codePathLocal: train_tpu_256_112cores.py
                cpu_count: 56
                cpu_count_logical: 112
                disk:
                    /:
                        total: "103865303040"
                        used: "64590647296"
                email: mkkang0412@gmail.com
                executable: /home/mkkang0412/Ouroboros/.venv/bin/python
                git:
                    commit: a67c386eea7b2fbd83874e16254eb3399388933e
                    remote: https://github.com/MK040412/Ouroboros.git
                host: t1v-n-8dff5040-w-0
                memory:
                    total: "202573803520"
                os: Linux-6.5.0-1013-gcp-x86_64-with-glibc2.35
                program: /home/mkkang0412/Ouroboros/train_tpu_256_112cores.py
                python: CPython 3.10.12
                root: /home/mkkang0412/Ouroboros
                startedAt: "2025-12-02T22:54:57.026683Z"
                tpu:
                    count: 4
                    devicesPerChip: 1
                    hbmGib: 16
                    name: v5e
                writerId: 37e4t5g4o1mvmbkep8j769rzjeqowf55
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 12
                - 45
            "2":
                - 1
                - 5
                - 11
                - 12
                - 45
                - 49
                - 53
                - 75
            "3":
                - 13
                - 16
            "4": 3.10.12
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
global_batch_size:
    value: 7168
learning_rate:
    value: 0.5
num_devices:
    value: 112
num_epochs:
    value: 20
tread_selection_rate:
    value: 0.5
